### ISSUE TITLE
Segmentation fault for two-phase models when --enable-vtk-output=true

### ISSUE THREAD

**Issue by GerryR** [OPM/opm-simulators#2639]
I installed opm and flow on a macbook using [these instructions](https://opm-project.org/?page_id=239) and it seems everything is working as expected. However, if I try to add the flag `--enable-vtk-output=true`, I get a segmentation error:
```
Writing visualization results for the current time step.
[1]    48068 segmentation fault  flow --enable-vtk-output=true 
```
I also had to add the `--output-dir=/path/to/output` flag (otherwise I get the exception `No directory for output specified`).

More details:
- flow version: `flow 2020.04-pre`
- OS: Darwin x86_64 (Kernel: 19.4.0)

**Comment by atgeirr** [comment]
I have the same kernel, and the option works for me, so I cannot reproduce. Are you on a recent master version of OPM? (I see we have forgotten to update the version name, current master should be called 2020.10-pre.)

There is a problem with names of some VTK output files, though. They seem to be named something with "sim" rather than the case name, causing possible confusion, and in the parallel case, failure to load the combined data.

**Comment by GerryR** [comment]
Now I am using the master branch for all the opm modules (last commit is on Tue May 26, Merge pull request #2634). Should I checkout to the latest release (release/2020.04) in all the opm modules?

**Comment by GerryR** [comment]
I tried one of the examples in opm-data (spe10model1), and the vtk output worked well. The main difference is that I was using only 2 phases (oil and water) in my deck. If I add the gas phase, the vtk output works also for my deck.

**Comment by atgeirr** [comment]
> The main difference is that I was using only 2 phases (oil and water) in my deck. If I add the gas phase, the vtk output works also for my deck.

That is useful, thanks for the discovery! I can reproduce this with a small two-phase model.

**Comment by atgeirr** [comment]
The two-phase bug and more is addressed in OPM/opm-models#613 and #2643.

**Comment by atgeirr** [comment]
Turns out we also needed OPM/opm-material#420 to make all smooth. All has been merged, so I'll close this issue as resolved.

**Comment by GerryR** [comment]
Thanks for the quick bugfix. Unfortunately, I still get the error when using a two-phase simulation. I also tried to add the check:
```
if (!FluidSystem::phaseIsActive(phaseIdx)) {
    continue;
}
```
to other locations in the `vtkmultiphasemodule.hh` where there is a loop over the phase index, but it didn't work.

**Comment by atgeirr** [comment]
I forgot to test the fix with a water-oil case, oops! Addressed in OPM/opm-models#614. I'll reopen the issue, until you confirm it is fixed.

**Comment by atgeirr** [comment]
The latest fix has been merged, it should resolve your problem.

**Comment by GerryR** [comment]
It works! The gas phase variables are still included in the vtu files, but they are all set to zero now.
