### ISSUE TITLE
CO2STORE: DRSDTCON and hysteresis behave differently in 2022.10

### ISSUE THREAD

**Issue by lrijkels** [OPM/opm-simulators#4318]
It seems that 2022.10 behaves a little differently from 2022.04 when using hysteresis in a DATA file with DRSDTCON switched on for CO2STORE. It is as if the bookkeeping of gas in liquid and gas phase goes wrong. The figure below shows an extreme example. It displays a long run with relperm hysteresis only, in 2022.10. DRSDTCON = 0.04. The deck simulates injection for 25 years and then monitors the plume for a few 1000 years. 
![image](https://user-images.githubusercontent.com/86057047/207137636-4c78ffff-272b-4283-aac9-a4170fa10090.png)
It appears that more gas dissolves into water (FGIPL) than disappears from the gas phase (FGIPG) and as a result the total gas in place (FGIP) keeps increasing - with the injectors shut in. This behaviour did not happen in 2022.04. In tests of this big model, it only occurs when both
- DRSDTCON is switched on (DRSDT does not do it)
- Hysteresis is switched on (the behaviour is absent in runs without hysteresis)
I tried to isolate the issue further in a simple DATA file, but I cannot reproduce it entirely. The attached example where I introduced hysteresis into the CO2STORE example DATA file does show different behaviour under 2022.04 and 2022.10. I hope that that is sufficient to track down what is happening. If not, I can try to trim down the bigger file so that it can be sent more easily.
Kind regards
Lex Rijkels
[CO2STORE_DRSDTCON_2022_10.DATA.TXT](https://github.com/OPM/opm-simulators/files/10211496/CO2STORE_DRSDTCON_2022_10.DATA.TXT)

**Comment by lrijkels** [comment]
Correction/addition: the increasing FGIP also occurs with DRSDT, not just with DRSDTCON. When I made DRSDT small (0.0004) the FGIP also continued to grow, despite no injection (FGIT remained flat). So it seems to be related to the combination of hysteresis and dissolution in 2022.10.

**Comment by totto82** [comment]
Have you tried to run the model with stricter tolerances for instance: --linear-solver-reduction=0.03 and --tolerance-mb=1e-7 and maybe also --tolerance-cnv-relaxed=0.01 I recently experiences a similar problem (but for a case with DISGAS without DRSDTCON nor DRSDT) and solving it more strict helped. I didn't know that this was not an issue (or less an issue) in 2022.04, that was very helpful to know. I will investigate further.

**Comment by lrijkels** [comment]
Tightening the first two tolerances made no difference, the model is now running with all 3 suggestions. I am also running a case without DRSDT and DRSDTCON (so only DISGAS) to see if that responds differently.

**Comment by lrijkels** [comment]
Update: tightening tolerances using all three options did not make 2022.10 behave like 2022.04. Running 2022.10 without DRSDT does make it behave like 2022.04 though, so the new behaviour is related to DRSDT/DRSDTCON. In a run with DRSDT=0.04 I did not notice it at first; when I made DRSDT=0.0004 the FGIP started increasing again, without injection. So it seems to show up only when DRSDT is restricted to small values (or using DRSDTCON, which seems to have the same effect). 
In the modified CO2STORE example I attached to the first post, FGIP behaves differently only when DRSDTCON is on AND relperm hysteresis is used. (The bigger data files I tested also use that combination.)
- If I remove the imbibition SGOF table (and the hysteresis keywords, and TABDIMS->1), 2022.10 behaves just like 2022.04 again.
- If I remove just DRSDTCON (but leave hysteresis on) 2022.10 also behaves the same as 2022.04.
So the combination of hysteresis and DRSDT(CON) leads to different behaviour in 2022.10. I tried both Carlson and Killough for the hysteresis model, but that made no difference.

**Comment by lrijkels** [comment]
This is what happens in the CO2STORE_DRSDTCON_2022_10 example:
![image](https://user-images.githubusercontent.com/86057047/207428434-f92a3f74-1f5f-4fe7-b2c2-a24c5edf5889.png)
This run has hysteresis and DRSDTCON; the gas in place keeps increasing after gas injection stops in 2022.10. In 2022.04 FGIP remained flat at the same level as FGIT.

**Comment by totto82** [comment]
I have found the issue. It is related to the new (and faster) linearizer and DRSDT which is included in the new release. Fortunately DIFFUSE was not implemented with the new linearizer so you could try to run your case with the DIFFUSE option. I will try to make a PR with a fix.

**Comment by lrijkels** [comment]
Great. Indeed, with DIFFUSE on the erroneous growth in FGIP disappears from my small test case - without a significant effect on other results or runtime so far. I am now running my big model again, also with diffusion. If that also shows that the problem is absent, shall I close this issue? Or do you prefer to keep it open until the linearizer has been fixed?

**Comment by totto82** [comment]
Good. I can close it when the fix is merged.

**Comment by atgeirr** [comment]
Should be fixed in #806.

**Comment by lrijkels** [comment]
Unfortunately the issue still seems to be present in 2023.04. I just tested a large test case and the one attached in the beginning of this issue. The Gas In Place (FGIP) is still growing after the gas injection (FGIT) stops. This happened in 2022.10, but not in 2022.04. Shall I open a new issue? Or can this one be re-opened?

**Comment by atgeirr** [comment]
Are you able to test the current master version? This issue should have been fixed in #806, unfortunately this was after the 2023.04 release, but it will be in 2023.10.

**Comment by lrijkels** [comment]
Ah, thanks, that explains why 2023.04 still had the issue. I'll figure out how to run the current master version (hopefully without screwing up my current package installation) and report back. But if you have the master, the simple DATA file in the beginning of the issue illustrates the issue. It is a slightly modified example file from OPM, which runs in a minute or so. After a short injection period, FGIT stops increasing. In 2022.10 (and 2023.04) FGIP continued to increase, however, essentially creating gas out of nowhere. 2022.04 modelled correctly that FGIP also stopped.

**Comment by lrijkels** [comment]
Good news, then we'll wait for the fix being delivered with 2023.10.
