### ISSUE TITLE
Initialization by Enumeration not working properly for some combinations of SGAS and PRESSURE

### ISSUE THREAD

**Issue by stimyd** [OPM/opm-simulators#6073]
Hello,

I have observed a few cases in my past use of Flow where initialization by "Enumeration" (i.e., initializing the model using the keywords PRESSURE, SGAS, SWAT, RV and RS) can sometimes result in a different initial state of the model than specified. 

I've attached two file decks. Same input files, with one deck having the output files from an ECL100 2012.1 run, and the other from a Flow 2023.04 run. 

In summary, OPM Flow initializes the model with SOIL = 0.4, when in fact, it should be 0.0. ECL100 initializes the model correctly. The wrong initialization subsequently causes convergence issues immediately. If PRESSURE is reduced to 6400 psia, then everything runs fine, but the initialization is still slightly wrong with SOIL close to, but not quite equal to 0.0. You can also observe that BPR of cell 1 1 1 seems to be increasing with time in Flow. A material-balance calculation issue perhaps?

Any thoughts on why this might be happening, and/or suggested solutions to the problem? 

[ecl100.zip](https://github.com/user-attachments/files/19212151/ecl100.zip)
[opm-flow.zip](https://github.com/user-attachments/files/19212154/opm-flow.zip)

**Comment by blattms** [comment]
I have not looked into this. It seems like you are using OPM flow 2023.04, which is rather old. The current version is 2024.10. Is there for a reason for using that version? 

I am not saying that this is fixed now but there at least is a chance. We usually do quite a few bug fixes during 1.5 years.

**Comment by daavid00** [comment]
I have run the case with master from today and the initialisation for SOIL looks fine, i.e., if run with the flag `--enable-vtk-output=1` (to look directly to the arrays values in the .vtu using a text editor) and adding: 

> RPTRST
> 'BASIC=2'/

in the `SOLUTION` section, then the initial `SOIL` is practically 0 (1.11022e-16).

**Comment by stimyd** [comment]
Hi

Thanks for getting back so quickly! 

I've have now tried running the case with Flow 2024.10 and the issue is still there (see attached .zip -> BSOIL is still 0.4 in .RSM, and the simulation continues to fail if I run it longer than a few seconds).

If it works on master, is there a potential fix to this coming with 2025.04?

![Image](https://github.com/user-attachments/assets/d2d80591-f721-40f5-b6c6-8dd8325c8a47)

[flow-202410.zip](https://github.com/user-attachments/files/19227020/flow-202410.zip)

**Comment by daavid00** [comment]
Hei, I just tested with 2024.10 and it seems correct. The oil saturation seems to appear after the well PROD is open. If you set in line 41 column 2 in the SCHEDULE.INC to SHUT instead of OPEN, then the BSOIL is practically zero (note that summary variables do not write the initial values (the time in the png you sent starts from 0.000012))

**Comment by stimyd** [comment]
Not sure I follow. Open versus shut well at 0.000012 days (=1 sec) after model initialization should not result in a 0.4 difference in oil saturation.  

The fluid system is an undersaturated gas condensate with a dewpoint pressure of 4934.1 psia. The cell pressure in cell 1 1 1 is 6499.889 psia at time=0.000012, as you can see from the BPR column in my screenshot above. There shouldn't be any oil in the cell at that pressure, but BSOIL in the same cell is 0.40000 at time=0.000012. 

I have also compiled flow from master and tested it, same problem there.

**Comment by daavid00** [comment]
Oh, since the issue was named as "Initialization by ...." I was just looking at the actual initial solution. It seems also the RS and RV are not in equilibrium, i.e., if again the PROD is shut those values changes from 1.7644E+00 and 1.0276E-01 to 4.61 and 0.216 respectively.

**Comment by daavid00** [comment]
Hi @stimyd, https://github.com/OPM/opm-simulators/pull/6079 was just merged, so you could rebuild Flow from master and test again your case. Thanks for raising this issue.

**Comment by stimyd** [comment]
Thank you for reviewing this and creating a fix. Highly appreciated! I will rebuild from master and try again. I'll close this issue once I've confirmed the problem has been resolved.

**Comment by stimyd** [comment]
I can confirm #6079 resolved the issue. Thanks again 👍
